export RSTUDIO_PANDOC=/Applications/RStudio.app/Contents/MacOS/pandoc

python3 ../code/taxolotl.py dochtml newlog

python3 ../code/taxolotl.py --description | sed 's/^/# /' > ../Taxolotl.md
echo >> ../Taxolotl.md

echo '```' >> ../Taxolotl.md
python3 ../code/taxolotl.py --details >> ../Taxolotl.md
echo '```' >> ../Taxolotl.md
echo >> ../Taxolotl.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/taxolotl.docs.html`](./docs/taxolotl.docs.html), or visit <https://slimsuite.github.io/taxolotl/>.' >> ../Taxolotl.md
echo 'Documentation can also be generated by running Taxolotl with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../Taxolotl.md
echo >> ../Taxolotl.md
echo '## Introduction' >> ../Taxolotl.md
echo >> ../Taxolotl.md
grep -A 10000 "Taxolotl combines" taxolotl.docs.Rmd >> ../Taxolotl.md

cp taxolotl.docs.html ../index.html
cp ../Taxolotl.md ../README.md
